export { default as OutlineIcon } from './OutlineIcon';
export { default as CompletionSolidIcon } from './CompletionSolidIcon';
export { default as EditSquareIcon } from './EditSquareIcon';
export { default as VideocamIcon } from './VideocamIcon';
export { default as VideocamCompleteIcon } from './VideocamCompleteIcon';
export { default as EditSquareCompleteIcon } from './EditSquareCompleteIcon';
export { default as BookIcon } from './BookIcon';
export { default as BookCompleteIcon } from './BookCompleteIcon';
export { default as DashedCircleIcon } from './DashedCircleIcon';
